spring:
  datasource:
    url:
    driver-class-name:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
    show-sql:
    properties:
      hibernate:
        format_sql:
    database:
    database-platform: